### ISSUE TITLE
Pets no respect Region flags

### ISSUE THREAD

**Issue by MizukageMaTes** [TheBusyBiscuit/HotbarPets#23]
Damaging pets do not respect the redprotect protection system flags.

**Comment by TheBusyBiscuit** [comment]
Hi, please follow the bug reporting template found here:
https://github.com/TheBusyBiscuit/HotbarPets/issues/new/choose

Make sure to also include what exact pets you are talking about, providing screenshots and videos as possible and most importantly... giving versions info.
